
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: neuroshield
      POSTGRES_PASSWORD: neuroshield
      POSTGRES_DB: neuroshield
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - neuroshield-network

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://neuroshield:neuroshield@postgres:5432/neuroshield
      PORT: 5000
      JWT_SECRET: your_jwt_secret
      ML_SERVICE_URL: http://ml-service:8000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - neuroshield-network

  ml-service:
    build:
      context: ./ml_service
    ports:
      - "8000:8000"
    networks:
      - neuroshield-network

networks:
  neuroshield-network:
    driver: bridge

volumes:
  postgres-data:
